var group___r_e_n_e_s_a_s___m_o_d_u_l_e_s =
[
    [ "Analog to Digital Converter (r_adc)", "group___a_d_c.html", "group___a_d_c" ],
    [ "Bus State Controller (r_bsc)", "group___b_s_c.html", "group___b_s_c" ],
    [ "Clock Generation Circuit (r_cgc)", "group___c_g_c.html", "group___c_g_c" ],
    [ "Compare Match Timer (r_cmt)", "group___c_m_t.html", "group___c_m_t" ],
    [ "Compare Match Timer W (r_cmtw)", "group___c_m_t_w.html", "group___c_m_t_w" ],
    [ "Controller Area Network - Flexible Data (r_canfd)", "group___c_a_n_f_d.html", "group___c_a_n_f_d" ],
    [ "Delta-sigma interface (r_dsmif)", "group___d_s_m_i_f.html", "group___d_s_m_i_f" ],
    [ "Direct Memory Access Controller (r_dmac)", "group___d_m_a_c.html", "group___d_m_a_c" ],
    [ "EtherCAT SSC Port (rm_ethercat_ssc_port)", "group___r_m___e_t_h_e_r_c_a_t___s_s_c___p_o_r_t.html", "group___r_m___e_t_h_e_r_c_a_t___s_s_c___p_o_r_t" ],
    [ "Ethernet (r_gmac)", "group___e_t_h_e_r.html", "group___e_t_h_e_r" ],
    [ "Ethernet PHY (r_ether_phy)", "group___e_t_h_e_r___p_h_y.html", "group___e_t_h_e_r___p_h_y" ],
    [ "Ethernet SELECTOR (r_ether_selector)", "group___e_t_h_e_r___s_e_l_e_c_t_o_r.html", "group___e_t_h_e_r___s_e_l_e_c_t_o_r" ],
    [ "Ethernet Switch (r_ethsw)", "group___e_t_h_s_w.html", "group___e_t_h_s_w" ],
    [ "Event Link Controller (r_elc)", "group___e_l_c.html", "group___e_l_c" ],
    [ "Expanded Serial Peripheral Interface (xSPI) OSPI (r_xspi_ospi)", "group___x_s_p_i___o_s_p_i.html", "group___x_s_p_i___o_s_p_i" ],
    [ "Expanded Serial Peripheral Interface (xSPI) QSPI (r_xspi_qspi)", "group___x_s_p_i___q_s_p_i.html", "group___x_s_p_i___q_s_p_i" ],
    [ "FreeRTOS Plus TCP (rm_freertos_plus_tcp)", "group___f_r_e_e_r_t_o_s___p_l_u_s___t_c_p.html", null ],
    [ "FreeRTOS Port (rm_freertos_port)", "group___r_m___f_r_e_e_r_t_o_s___p_o_r_t.html", null ],
    [ "General PWM Timer (r_gpt)", "group___g_p_t.html", "group___g_p_t" ],
    [ "General PWM Timer Three-Phase Motor Control Driver (r_gpt_three_phase)", "group___g_p_t___t_h_r_e_e___p_h_a_s_e.html", "group___g_p_t___t_h_r_e_e___p_h_a_s_e" ],
    [ "General PWM Timer phase count Motor Control Driver (r_gpt_phase_count)", "group___g_p_t___p_h_a_s_e___c_o_u_n_t.html", "group___g_p_t___p_h_a_s_e___c_o_u_n_t" ],
    [ "I/O Ports (r_ioport)", "group___i_o_p_o_r_t.html", "group___i_o_p_o_r_t" ],
    [ "I2C Master on IIC (r_iic_master)", "group___i_i_c___m_a_s_t_e_r.html", "group___i_i_c___m_a_s_t_e_r" ],
    [ "I2C Slave on IIC (r_iic_slave)", "group___i_i_c___s_l_a_v_e.html", "group___i_i_c___s_l_a_v_e" ],
    [ "Inter-CPU IRQ on ICU (r_icu_inter_cpu_irq)", "group___i_c_u___i_n_t_e_r___c_p_u___i_r_q.html", "group___i_c_u___i_n_t_e_r___c_p_u___i_r_q" ],
    [ "Multi-Function Timer Pulse Unit 3 (r_mtu3)", "group___m_t_u3.html", "group___m_t_u3" ],
    [ "Multi-Function Timer Pulse Unit 3 Three-Phase Motor Control Driver (r_mtu3_three_phase)", "group___m_t_u3___t_h_r_e_e___p_h_a_s_e.html", "group___m_t_u3___t_h_r_e_e___p_h_a_s_e" ],
    [ "Multi-Function Timer Pulse Unit 3 phase count Motor Control Driver (r_mtu3_phase_count)", "group___m_t_u3___p_h_a_s_e___c_o_u_n_t.html", "group___m_t_u3___p_h_a_s_e___c_o_u_n_t" ],
    [ "Port Output Enable 3 (r_poe3)", "group___p_o_e3.html", "group___p_o_e3" ],
    [ "Port Output Enable for GPT (r_poeg)", "group___p_o_e_g.html", "group___p_o_e_g" ],
    [ "Serial Communications Interface (SCI) UART (r_sci_uart)", "group___s_c_i___u_a_r_t.html", "group___s_c_i___u_a_r_t" ],
    [ "Serial Peripheral Interface (r_spi)", "group___s_p_i.html", "group___s_p_i" ],
    [ "Shared Memory (r_shared_memory)", "group___s_h_a_r_e_d___m_e_m_o_r_y.html", "group___s_h_a_r_e_d___m_e_m_o_r_y" ],
    [ "USB (r_usb_basic)", "group___u_s_b.html", "group___u_s_b" ],
    [ "USB Host Communications Device Class Driver (r_usb_hcdc)", "group___u_s_b___h_c_d_c.html", null ],
    [ "USB Peripheral Communications Device Class (r_usb_pcdc)", "group___u_s_b___p_c_d_c.html", null ]
];