var group___r_e_n_e_s_a_s___i_n_t_e_r_f_a_c_e_s =
[
    [ "ADC Interface", "group___a_d_c___a_p_i.html", "group___a_d_c___a_p_i" ],
    [ "Block Media Interface", "group___r_m___b_l_o_c_k___m_e_d_i_a___a_p_i.html", "group___r_m___b_l_o_c_k___m_e_d_i_a___a_p_i" ],
    [ "CAN Interface", "group___c_a_n___a_p_i.html", "group___c_a_n___a_p_i" ],
    [ "CGC Interface", "group___c_g_c___a_p_i.html", "group___c_g_c___a_p_i" ],
    [ "CRC Interface", "group___c_r_c___a_p_i.html", "group___c_r_c___a_p_i" ],
    [ "DOC Interface", "group___d_o_c___a_p_i.html", "group___d_o_c___a_p_i" ],
    [ "ELC Interface", "group___e_l_c___a_p_i.html", "group___e_l_c___a_p_i" ],
    [ "ERROR Interface", "group___e_r_r_o_r___a_p_i.html", "group___e_r_r_o_r___a_p_i" ],
    [ "EtherCAT SSC Interface", "group___e_t_h_e_r_c_a_t___s_s_c___p_o_r_t___a_p_i.html", "group___e_t_h_e_r_c_a_t___s_s_c___p_o_r_t___a_p_i" ],
    [ "Ethernet Interface", "group___e_t_h_e_r___a_p_i.html", "group___e_t_h_e_r___a_p_i" ],
    [ "Ethernet PHY Interface", "group___e_t_h_e_r___p_h_y___a_p_i.html", "group___e_t_h_e_r___p_h_y___a_p_i" ],
    [ "Ethernet Selector Interface", "group___e_t_h_e_r___s_e_l_e_c_t_o_r___a_p_i.html", "group___e_t_h_e_r___s_e_l_e_c_t_o_r___a_p_i" ],
    [ "Ethernet Switch Interface", "group___e_t_h_s_w___a_p_i.html", "group___e_t_h_s_w___a_p_i" ],
    [ "External Bus Interface", "group___e_x_t_e_r_n_a_l___b_u_s___a_p_i.html", "group___e_x_t_e_r_n_a_l___b_u_s___a_p_i" ],
    [ "External IRQ Interface", "group___e_x_t_e_r_n_a_l___i_r_q___a_p_i.html", "group___e_x_t_e_r_n_a_l___i_r_q___a_p_i" ],
    [ "I/O Port Interface", "group___i_o_p_o_r_t___a_p_i.html", "group___i_o_p_o_r_t___a_p_i" ],
    [ "I2C Master Interface", "group___i2_c___m_a_s_t_e_r___a_p_i.html", "group___i2_c___m_a_s_t_e_r___a_p_i" ],
    [ "I2C Slave Interface", "group___i2_c___s_l_a_v_e___a_p_i.html", "group___i2_c___s_l_a_v_e___a_p_i" ],
    [ "Inter CPU IRQ Interface", "group___i_c_u___i_n_t_e_r___c_p_u___i_r_q___a_p_i.html", "group___i_c_u___i_n_t_e_r___c_p_u___i_r_q___a_p_i" ],
    [ "NOR Flash Interface", "group___n_o_r___f_l_a_s_h___a_p_i.html", "group___n_o_r___f_l_a_s_h___a_p_i" ],
    [ "POE3 Interface", "group___p_o_e3___a_p_i.html", "group___p_o_e3___a_p_i" ],
    [ "POEG Interface", "group___p_o_e_g___a_p_i.html", "group___p_o_e_g___a_p_i" ],
    [ "Phase count Interface", "group___g_p_t___p_h_a_s_e___c_o_u_n_t___a_p_i.html", "group___g_p_t___p_h_a_s_e___c_o_u_n_t___a_p_i" ],
    [ "Phase count Interface", "group___m_t_u3___p_h_a_s_e___c_o_u_n_t___a_p_i.html", "group___m_t_u3___p_h_a_s_e___c_o_u_n_t___a_p_i" ],
    [ "RTC Interface", "group___r_t_c___a_p_i.html", "group___r_t_c___a_p_i" ],
    [ "SDRAM Interface", "group___s_d_r_a_m___a_p_i.html", "group___s_d_r_a_m___a_p_i" ],
    [ "SPI Flash Interface", "group___s_p_i___f_l_a_s_h___a_p_i.html", "group___s_p_i___f_l_a_s_h___a_p_i" ],
    [ "SPI Interface", "group___s_p_i___a_p_i.html", "group___s_p_i___a_p_i" ],
    [ "Shared Memory Interface", "group___s_h_a_r_e_d___m_e_m_o_r_y___a_p_i.html", "group___s_h_a_r_e_d___m_e_m_o_r_y___a_p_i" ],
    [ "Three-Phase Interface", "group___t_h_r_e_e___p_h_a_s_e___a_p_i.html", "group___t_h_r_e_e___p_h_a_s_e___a_p_i" ],
    [ "Timer Interface", "group___t_i_m_e_r___a_p_i.html", "group___t_i_m_e_r___a_p_i" ],
    [ "Transfer Interface", "group___t_r_a_n_s_f_e_r___a_p_i.html", "group___t_r_a_n_s_f_e_r___a_p_i" ],
    [ "UART Interface", "group___u_a_r_t___a_p_i.html", "group___u_a_r_t___a_p_i" ],
    [ "USB HCDC Interface", "group___u_s_b___h_c_d_c___a_p_i.html", "group___u_s_b___h_c_d_c___a_p_i" ],
    [ "USB HHID Interface", "group___u_s_b___h_h_i_d___a_p_i.html", "group___u_s_b___h_h_i_d___a_p_i" ],
    [ "USB Interface", "group___u_s_b___a_p_i.html", "group___u_s_b___a_p_i" ],
    [ "USB PCDC Interface", "group___u_s_b___p_c_d_c___a_p_i.html", "group___u_s_b___p_c_d_c___a_p_i" ],
    [ "USB PMSC Interface", "group___u_s_b___p_m_s_c___a_p_i.html", "group___u_s_b___p_m_s_c___a_p_i" ],
    [ "WDT Interface", "group___w_d_t___a_p_i.html", "group___w_d_t___a_p_i" ]
];